### ISSUE TITLE
Intermittent 503 responses

### ISSUE THREAD

**Issue by challengee** [batchblue/batchbook-api#16]
Hi guys,

We're getting 503 unavailable errors when creating a bunch of contacts through the API. We're trying to create 240 contacts but only 100-150 are actually created on first try. The others fail with:

```
"<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.6.0</center>\r\n</body>\r\n</html>\r\n
```

Is this some kind of rate limiting on your side or is there a problem with the API currently?

Thanks!

**Comment by randerson** [comment]
We do currently answer requests that exceed our rate limits with a 503.
